// shadcn/ui utility — merges Tailwind class names with clsx + tailwind-merge.
// This file is generated by shadcn init and must stay at @/lib/utils.

import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
